apiVersion: dtps/v1
kind: Deployment
metadata:
  name: dtps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dtps
  template:
    metadata:
      labels:
        app: dtps
    spec:
      containers:
        - name: dtps
          image: projects2025-app:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          env:
            - name: NODE_ENV
              value: "production"
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq"
            - name: DATABASE_URL
              value: "postgres://user:password@postgres:5432/distributed_systems_db"
