apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: prisma-migrate
          image: effemm/dtps-app:v1.3
          command: ["npx", "prisma", "migrate", "deploy"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: DATABASE_URL
      restartPolicy: Never
