apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: effemm/dtps-pdf_worker:v1.3
          command: ["npx", "ts-node", "src/workers/pdfConversionWorker.ts"]
          env:
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: RABBITMQ_URL
            - name: CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: CLOUD_NAME
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: API_KEY
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: API_SECRET
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: SECRET_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: DATABASE_URL
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
