apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: effemm/projects2025-pdf-worker:latest
          command: ["npx", "ts-node", "src/workers/pdfConversionWorker.ts"]
          env:
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
