apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  RABBITMQ_URL: YW1xcDovL3JhYmJpdG1x
  CLOUD_NAME: ZHJ5N3NldGN6
  API_KEY: MTkxOTI5NjUzMzI3NTEz
  API_SECRET: MmxoSm5zZFpMQUJaZkF1SW1KeTl3QzJFNGlv
  SECRET_KEY: c2VjcmV0X0Eyb3JxSE15TXFsVU1ZMlU=
  DATABASE_URL: cG9zdGdyZXM6Ly91c2VyOnBhc3N3b3JkQHBvc3RncmVzOjU0MzIvZGlzdHJpYnV0ZWRfc3lzdGVtc19kYg==
